### ISSUE TITLE
Watch scss folder

### ISSUE THREAD

**Issue by rocchidavide** [babobski/Komodo-sass-compiler#1]
Thank you for your work!
Is it possible to watch a folder?

**Comment by babobski** [comment]
Currently this is not possible, the only option you current have is to enable a "file watcher". You select one file you want to output, when editing less files.

I'm always open for requests, the file watcher function is currently pretty basic. Currently I'm working on my less compiler(the sass compiler is based on the less compiler), to beef up the autocomplete function. I will take a look at the file watcher function while I'm at it, if i can make some improvement there.

The only question i have, is what do you mean with "watch a folder".
Do you want to select a output file, and select the folder when working in this folder, will trigger the output file?
Or do you mean, the same as above only with multiple file scopes, so you can work with multiple less/scss files in you're project?

**Comment by babobski** [comment]
Added a file scope functionality in the latest release, you can set a output file and select a output folder.
When you edit a file in the scope the output file will be triggerd
