### ISSUE TITLE
Can't add new scope

### ISSUE THREAD

**Issue by nrigaudiere** [babobski/Komodo-sass-compiler#10]
Hi,
I have been trying to create a new scope on Komodo IDE 10.2 and I keep getting the following message :

![capture d ecran 2017-09-05 a 15 05 19](https://user-images.githubusercontent.com/5648148/30062508-b815a6e2-924b-11e7-9251-65dc07932c45.png)
 

Regards.

**Comment by babobski** [comment]
@nrigaudiere currently the file scopes are based on you're projects.
You need to have a active project open to create a file scope.
