### ISSUE TITLE
Doesn't like my code

### ISSUE THREAD

**Issue by CeriW** [babobski/Komodo-sass-compiler#5]
Hi,

Must say, I've been having great difficulty getting this to work. I've tried it on Komodo Edit 8, 9 and 10. It won't open at all in 8, and says it's incompatible with 9 and 10, but what is it compatible with?

The issues I've been having:
1. After I declare a variable like this for example:
   $main: #00aaee;

It doesn't let me use it, the autocomplete doesn't work. It won't even let me insert a dollar sign using my keyboard, but if I copy and paste $main in to use it, it works and compiles fine.
1. It's telling me my code is invalid when it's actually fine. The CMS I use allows the following markup:

@breakpoint >=l{
  css code here
}

as a way of doing media queries where the breakpoints are defined elsewhere. However, it won't compile if I do this. Is there a way I can tell it to ignore this?

I'm excited to use SCSS but it's proving very difficult so far!

**Comment by babobski** [comment]
@CeriW Thanks for the report.
How are you istalling the sass compiler? from within komodo?

When I install the addon trough komodo it is also not working for me, when I install the [latest version](https://github.com/babobski/Komodo-sass-compiler/releases/tag/2.3) from github it's working.

**Comment by babobski** [comment]
@CeriW the incompatible with notification should only appear in komodo 8 and 9 as the latest version only supports Komodo X. For komodo 8.5 - 9 You can use the [version 2.1](https://github.com/babobski/Komodo-sass-compiler/releases/tag/2.1-beta)

**Comment by CeriW** [comment]
I'm using Komodo 10.0.1 on a Mac and just can't get it to work.

How do I go about installing from outside of Komodo? Sorry if it's a dumb question, this kind of stuff doesn't come naturally for me.

**Comment by babobski** [comment]
To download outside komodo you can download the .xpi form github ( you need to save link as, or else it tries to install it in firefox ).
You than only have to drop the .xpi file on komodo. 
Tested it some more this weekend but there is no difference between the version downloaded inside komodo and the one on github.

A bug i found in the sasss compiler, is when you start a new file, without a file location and you began to type a $var before the file is saved, the completion fails. When i then reopen the file the autocompletion is working.

Are you working with new files or with existing files? And does the autocompletion never works or in some cases?

**Comment by CeriW** [comment]
I've never been able to get the autocompletion to work, it just doesn't let me type a $. However, if I copy and paste a variable in, it compiles as you'd expect it to.

I've tried creating a new file and then saving, doesn't work. I've also saved a new SCSS file, closed it then opened it again and still doesn't work.

When I try dragging the .xpi file into Komodo, I get a screen of code. 
![screen shot 2016-07-11 at 09 46 59](https://cloud.githubusercontent.com/assets/18597781/16725485/5e3552f0-474f-11e6-8abe-c130dcba80ca.png)

**Comment by babobski** [comment]
@CeriW  Did you save it as xpi, or did you some how saved it as a .txt file?
A other way to do it is, to go to **Tools > addons (legacy)** if you click on the settings button in the top of the window you can choose the option **install addon from file**

Do you have any related errors in you're error log? (**Help > troubleshooting > view log file**)

**Comment by CeriW** [comment]
Hi again Bob,

Thank you so much for your patience!

I've downloaded the .xpi file (version 2.3, which I believe is the latest) from this page: https://github.com/babobski/Komodo-sass-compiler/releases/tag/2.3

I've downloaded it using Chrome, as Firefox tries to install it as an add on for itself. Chrome downloads it as Komodo-sass-compiler-2.3.xpi. All seems normal.

When I drag this file into Komodo, I get the screenshot in my previous post.

When I use the Add on (legacy) and install add on from file, it installs, but first I get a warning that it's not compatible.

![screen shot 2016-07-11 at 15 59 30](https://cloud.githubusercontent.com/assets/18597781/16735524/3f53dc12-4781-11e6-81f0-06e63830bc31.png)

Again, using Komodo 10.0.1 on a Mac.

**Comment by babobski** [comment]
Ah found what is the problem, the popup isn't working in Edit. 
There where a few changes regarding komodo X, only not all the changes for Ide also apply on Edit, also the version numbering is wrong for Edit where the max version is set to `10` and not `10.*`.
Will look in to this tonight and report back when the issues are fixed.

**Comment by babobski** [comment]
@CeriW the issues in Edit are fixed in the [latest release](https://github.com/babobski/Komodo-sass-compiler/releases/latest)

**Comment by babobski** [comment]
@CeriW how are you're settings for drag and drop (**Preferences > Editor**) maybe this is set wrong?
![2016-07-12 08_00_02](https://cloud.githubusercontent.com/assets/3530262/16756630/af70d3c6-4806-11e6-8a8c-3f1e69ec3488.png)

**Comment by CeriW** [comment]
Thanks babobski, the autocomplete is working just fine now with the latest release. Glad to know it wasn't just me being dense!

My drag and drop settings are set as they are in your screenshot, but it still opens the code. Have to go to Add ons (Legacy) and install from file but it works.

I did mention earlier on that the CMS I use allows us to define a set of breakpoints with names (usually XS, S, M, L and XL) and call these in the CSS as simplified media queries like this:

@breakpoint >=l{
  /_Rules that apply at only this screen size_/
}

But the compiler doesn't like this. Tells me it can't read anything after the >

Is there any way I can tell it to ignore this?

**Comment by babobski** [comment]
@CeriW did some more research how to get the `@breakpoint >= l` working.

Self I work with Less and in less you can simple escape a string with `~"escaped value"`.
For sass/scss you need to use [Interpolation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_) for this.

Found a nice [answer](http://stackoverflow.com/questions/20935792/how-can-i-escape-string-css-in-sass-scss) on stackoverflow and tweaked a bit with you're code to get it working.

``` scss
$breakLarge: unquote(">=l");

@breakpoint #{$breakLarge} { 
    color: #333;
}
```

This should do the trick.

**Comment by CeriW** [comment]
Thanks babobski, you are an absolute star. Shame it requires more typing than before, but I'll set up a snippet and I'll live!

**Comment by CeriW** [comment]
I do notice the compiler accepts ~"value" 

:)

**Comment by babobski** [comment]
@CeriW I do notice it will compile with ~"value", only this will not escape the value:

``` scss
@breakpoint ~">=l" { 
    color: #333;
}
```

Output:

``` css
@breakpoint ~ ">=l" {
  color: #333; }
```

If you use the Interpolation example, it will output in the syntax you want:

``` scss
$breakLarge: unquote(">=l");

@breakpoint #{$breakLarge} { 
    color: #333;
}
```

Output:

``` css
@breakpoint >=l {
  color: #333; }

```

**Comment by CeriW** [comment]
Hmm, that's weird. Could have sworn it worked yesterday, but not today.

Oh well!
