### ISSUE TITLE
Not compatible with Komodo Edit 8.5.4

### ISSUE THREAD

**Issue by bellingboe** [babobski/Komodo-sass-compiler#9]
![image](https://cloud.githubusercontent.com/assets/1373524/25569366/cc9e74ec-2ddb-11e7-8c40-926fd670e7c3.png)

But when I try to update, it doesn't work. What's wrong?

**Comment by babobski** [comment]
@bellingboe the latest release of the Sass compiler, is only compatible with Komodo X. 
There where some changes that made it pretty hard to still support the older versions of Komodo.

For Komodo 8.5.* - 9.* you can the [2.1-beta version](https://github.com/babobski/Komodo-sass-compiler/releases/tag/2.1-beta) of the Sass compiler, this is still compatible with Komodo 8.5.*
